# Generated by Django 2.1.1 on 2018-10-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20181022_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='D_O_B',
        ),
    ]
