# Generated by Django 2.1.1 on 2018-10-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_remove_userprofileinfo_d_o_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_of_Intersts', models.CharField(max_length=1000)),
                ('Skills', models.CharField(max_length=10000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.UserProfileInfo')),
            ],
        ),
    ]
