# Generated by Django 2.1.1 on 2018-10-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20181023_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='Area_of_Intersts',
            new_name='Area_of_Interests',
        ),
    ]
