# Generated by Django 2.1.1 on 2018-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20181023_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Area_of_Interests',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Extra_Skills',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
