# Generated by Django 2.1.1 on 2018-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_counsellor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('WEBPAGE', models.URLField()),
                ('CONTACT_NO', models.CharField(max_length=12)),
                ('EMAIL', models.EmailField(max_length=70)),
            ],
        ),
    ]
