# Generated by Django 2.1.1 on 2018-10-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_ngo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NGO',
            new_name='n_g_o',
        ),
    ]
