# Generated by Django 2.1.1 on 2018-10-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20181024_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate_organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Organization_name', models.CharField(max_length=1000)),
                ('Problem_faced', models.CharField(max_length=10000)),
                ('Suggestion', models.CharField(max_length=10000)),
            ],
        ),
    ]
